apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .KlusterletName }}
  namespace: "{{ .KlusterletNamespace }}"
{{- if .UseImagePullSecret }}
imagePullSecrets:
- name: "{{ .ImagePullSecretName }}"
{{- end}}
